[project]
name = "med-slim"
version = "0.1.0"
authors = [
  { name="Chia-Hao Chang", email="chia.hao.chang@rwth-aachen.de" },
]
description = "MedSliM: Self-supervised pretraining of a sequence encoder over precomputed 2D foundation model slice features for 3D medical image analysis."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate==1.9.0",
    "editables",
    "hatchling",
    "causal-conv1d @ git+https://github.com/KatherLab/causal-conv1d.git@b73d1ca0e0726ba6520c38d342bd411bb5850064",
    "datasets==3.3.2",
    "dcm2niix",
    "einops==0.8.1",
    "flash-attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.6cxx11abiFALSE-cp312-cp312-linux_x86_64.whl",
    "grad-cam==1.5.5",
    "hf-transfer",
    "huggingface_hub==0.34.3",
    "ipykernel",
    "iterative-stratification==0.1.9",
    "kaggle==1.7.4",
    "lxt==2.1",
    "mamba-ssm @ git+https://github.com/KatherLab/mamba.git@d0d4192621889b26f9669ea4a8e6fe79cc84e8d9",
    "matplotlib-inline==0.1.7",
    "matplotlib==3.10.0",
    "numpy==2.2.5",
    "open-clip-torch>=2.23.0",
    "opencv-python==4.11.0.86",
    "pandas==2.2.3",
    "pillow==11.2.1",
    "pydicom==3.0.1",
    "pylidc",
    "pytest",
    "python-dotenv",
    "pyyaml==6.0.2",
    "safetensors==0.5.3",
    "scikit-image==0.25.2",
    "scikit-learn==1.6.1",
    "scipy==1.15.2",
    "seaborn==0.13.2",
    "sentencepiece==0.2.0",
    "setuptools",
    "supervision==0.25.1",
    "synapseclient",
    "timm==1.0.19",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "torchio>=0.20.14",
    "torchmetrics==1.7.1",
    "torchvision==0.21.0",
    "tqdm==4.67.1",
    "transformers>=4.51.3",
    "umap-learn>=0.5.11",
    "wandb==0.19.6",
    "mup>=1.0.0",
    "yacs>=0.1.8",
    "fvcore>=0.1.5.post20221221",
    "tenacity>=9.1.4",
]

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
# To allow referencing git repos in dependencies
allow-direct-references = true

[tool.hatch.build]
# Include all files/directories that start with 'med_slim'
include = ["med_slim*"]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]

