# Choices of pretrained slice encoder model configurations for image preprocessing
# Each model has specific image size and normalization parameters settings. 
# If there is a HuggingFace repository name for the model, it can be optionally added in the hf_repo field.

dinov2:
  img_size: [224, 224]
  image_mean: [0.485, 0.456, 0.406]
  image_std: [0.229, 0.224, 0.225]
  hf_repo: "facebook/dinov2-base"

rad-dino:
  img_size: [518, 518]
  image_mean: [0.5307, 0.5307, 0.5307]
  image_std: [0.2583, 0.2583, 0.2583]
  hf_repo: "microsoft/rad-dino"

medsiglip:
  img_size: [448, 448]
  image_mean: [0.5, 0.5, 0.5]
  image_std: [0.5, 0.5, 0.5]
  hf_repo: "google/medsiglip-448"

ark:
  img_size: [768, 768]
  image_mean: [0.485, 0.456, 0.406]
  image_std: [0.229, 0.224, 0.225]

biomedclip:
  img_size: [224, 224]
  image_mean: [0.48145466, 0.4578275, 0.40821073]
  image_std: [0.26862954, 0.26130258, 0.27577711]
  hf_repo: "microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224"
